/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlasmaRouteImport } from './routes/plasma'
import { Route as MatrixRouteImport } from './routes/matrix'
import { Route as MandelbrotRouteImport } from './routes/mandelbrot'
import { Route as LifeRouteImport } from './routes/life'
import { Route as LayoutRouteImport } from './routes/layout'
import { Route as FireRouteImport } from './routes/fire'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CounterRouteImport } from './routes/counter'
import { Route as IndexRouteImport } from './routes/index'

const PlasmaRoute = PlasmaRouteImport.update({
  id: '/plasma',
  path: '/plasma',
  getParentRoute: () => rootRouteImport,
} as any)
const MatrixRoute = MatrixRouteImport.update({
  id: '/matrix',
  path: '/matrix',
  getParentRoute: () => rootRouteImport,
} as any)
const MandelbrotRoute = MandelbrotRouteImport.update({
  id: '/mandelbrot',
  path: '/mandelbrot',
  getParentRoute: () => rootRouteImport,
} as any)
const LifeRoute = LifeRouteImport.update({
  id: '/life',
  path: '/life',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/layout',
  path: '/layout',
  getParentRoute: () => rootRouteImport,
} as any)
const FireRoute = FireRouteImport.update({
  id: '/fire',
  path: '/fire',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CounterRoute = CounterRouteImport.update({
  id: '/counter',
  path: '/counter',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/counter': typeof CounterRoute
  '/dashboard': typeof DashboardRoute
  '/editor': typeof EditorRoute
  '/fire': typeof FireRoute
  '/layout': typeof LayoutRoute
  '/life': typeof LifeRoute
  '/mandelbrot': typeof MandelbrotRoute
  '/matrix': typeof MatrixRoute
  '/plasma': typeof PlasmaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/counter': typeof CounterRoute
  '/dashboard': typeof DashboardRoute
  '/editor': typeof EditorRoute
  '/fire': typeof FireRoute
  '/layout': typeof LayoutRoute
  '/life': typeof LifeRoute
  '/mandelbrot': typeof MandelbrotRoute
  '/matrix': typeof MatrixRoute
  '/plasma': typeof PlasmaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/counter': typeof CounterRoute
  '/dashboard': typeof DashboardRoute
  '/editor': typeof EditorRoute
  '/fire': typeof FireRoute
  '/layout': typeof LayoutRoute
  '/life': typeof LifeRoute
  '/mandelbrot': typeof MandelbrotRoute
  '/matrix': typeof MatrixRoute
  '/plasma': typeof PlasmaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/counter'
    | '/dashboard'
    | '/editor'
    | '/fire'
    | '/layout'
    | '/life'
    | '/mandelbrot'
    | '/matrix'
    | '/plasma'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/counter'
    | '/dashboard'
    | '/editor'
    | '/fire'
    | '/layout'
    | '/life'
    | '/mandelbrot'
    | '/matrix'
    | '/plasma'
  id:
    | '__root__'
    | '/'
    | '/counter'
    | '/dashboard'
    | '/editor'
    | '/fire'
    | '/layout'
    | '/life'
    | '/mandelbrot'
    | '/matrix'
    | '/plasma'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CounterRoute: typeof CounterRoute
  DashboardRoute: typeof DashboardRoute
  EditorRoute: typeof EditorRoute
  FireRoute: typeof FireRoute
  LayoutRoute: typeof LayoutRoute
  LifeRoute: typeof LifeRoute
  MandelbrotRoute: typeof MandelbrotRoute
  MatrixRoute: typeof MatrixRoute
  PlasmaRoute: typeof PlasmaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/plasma': {
      id: '/plasma'
      path: '/plasma'
      fullPath: '/plasma'
      preLoaderRoute: typeof PlasmaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matrix': {
      id: '/matrix'
      path: '/matrix'
      fullPath: '/matrix'
      preLoaderRoute: typeof MatrixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mandelbrot': {
      id: '/mandelbrot'
      path: '/mandelbrot'
      fullPath: '/mandelbrot'
      preLoaderRoute: typeof MandelbrotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/life': {
      id: '/life'
      path: '/life'
      fullPath: '/life'
      preLoaderRoute: typeof LifeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/layout': {
      id: '/layout'
      path: '/layout'
      fullPath: '/layout'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fire': {
      id: '/fire'
      path: '/fire'
      fullPath: '/fire'
      preLoaderRoute: typeof FireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/counter': {
      id: '/counter'
      path: '/counter'
      fullPath: '/counter'
      preLoaderRoute: typeof CounterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CounterRoute: CounterRoute,
  DashboardRoute: DashboardRoute,
  EditorRoute: EditorRoute,
  FireRoute: FireRoute,
  LayoutRoute: LayoutRoute,
  LifeRoute: LifeRoute,
  MandelbrotRoute: MandelbrotRoute,
  MatrixRoute: MatrixRoute,
  PlasmaRoute: PlasmaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
